version: '3.5'

services:
  php-fpm:
    build: .
    depends_on:
      - mysql
    volumes:
      - .:/var/www/html
  nginx:
    image: nginx:latest
    depends_on:
      - php-fpm
    ports:
      - 8000:80
    volumes:
      - .:/var/www/html
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
    volumes:
      - db-data:/var/lib/mysql
  mysql-test:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}-test
  redis:
    image: redis
  meilisearch:
    image: getmeili/meilisearch
volumes:
  db-data:
